from django.urls import path

from .views import (
    ChildDetailView,
    ChildListCreateView,
    ChildStatsView,
    ChildStatusView,
    ChildTutorAssociationByChildView,
    ChildTutorAssociationByTutorView,
    ChildTutorAssociationDetailView,
    ChildTutorAssociationHistoryView,
    ChildTutorAssociationListCreateView,
    ChildTutorAssociationStatsView,
    EducationalCenterDetailView,
    EducationalCenterListCreateView,
    EducationalCenterStatsView,
    EducationalCenterStatusView,
    GPSDeviceAvailableView,
    GPSDeviceDetailView,
    GPSDeviceHistoryView,
    GPSDeviceListCreateView,
    GPSDeviceStatsView,
    GPSDeviceStatusView,
    GeographicLocationByChildView,
    GeographicLocationHistoryView,
    GeographicLocationRegisterView,
    LoginView,
    MobileLocationContextView,
    MobileChildrenListView,
    MobileChildAlertsView,
    MobileSecurityAlertsView,
    MobileSecurityAlertDetailView,
    MobileSecurityAlertStatsView,
    MobileSecurityAlertStatusUpdateView,
    MobileChildLocationHistoryExportView,
    MobileChildLocationHistorySearchView,
    MobileChildLocationHistoryView,
    MobileChildMapSummaryView,
    MobileChildMapContextView,
    MobileLocationHistoryDetailView,
    MonitoringAnalyzeView,
    MonitoringConfigView,
    MonitoringCurrentStatusView,
    MonitoringHistoryView,
    MonitoringMetricsView,
    ModuleListView,
    PermissionListView,
    RegentDetailView,
    RegentEducationalCenterOptionsView,
    RegentListCreateView,
    RegentOptionsView,
    RegentStatsView,
    RegentStatusView,
    RiskZoneCalculateView,
    RiskZoneDetailView,
    RiskZoneListCreateView,
    RiskZoneStatsView,
    RiskZoneStatusView,
    RiskZoneValidatePolygonView,
    RoleDetailView,
    RoleListCreateView,
    RoleStatsView,
    RoleStatusView,
    SafeAreaByCenterView,
    SafeAreaCalculateView,
    SafeAreaDetailView,
    SafeAreaHistoryView,
    SafeAreaListCreateView,
    SafeAreaStatsView,
    SafeAreaStatusView,
    SafeAreaValidatePolygonView,
    SecurityAlertsByChildView,
    SecurityAlertsView,
    SecurityAlertDetailView,
    SecurityAlertHistoryView,
    SecurityAlertStatsView,
    SecurityAlertStatusUpdateView,
    StudentActiveView,
    StudentByCenterView,
    StudentDetailView,
    StudentHistoryView,
    StudentListCreateView,
    StudentStatsView,
    StudentStatusView,
    StudentWithoutGpsView,
    TutorChildrenView,
    TutorDetailView,
    TutorListCreateView,
    TutorMobileAccountView,
    TutorResetPasswordView,
    TutorStatsView,
    TutorStatusView,
    UserDetailView,
    UserListCreateView,
    UserStatsView,
    UserStatusView,
)

urlpatterns = [
    path("auth/login/", LoginView.as_view(), name="login"),
    path("users/", UserListCreateView.as_view(), name="users-list-create"),
    path("users/stats/", UserStatsView.as_view(), name="users-stats"),
    path("users/<int:user_id>/", UserDetailView.as_view(), name="users-detail"),
    path("users/<int:user_id>/status/", UserStatusView.as_view(), name="users-status"),
    path("mobile/children/", MobileChildrenListView.as_view(), name="mobile-children"),
    path("mobile/children/<int:child_id>/map-summary/", MobileChildMapSummaryView.as_view(), name="mobile-child-map-summary"),
    path("mobile/children/<int:child_id>/location/history/", MobileChildLocationHistoryView.as_view(), name="mobile-child-location-history"),
    path("mobile/children/<int:child_id>/location-history/export/", MobileChildLocationHistoryExportView.as_view(), name="mobile-child-location-history-export"),
    path("mobile/children/<int:child_id>/location-history/", MobileChildLocationHistorySearchView.as_view(), name="mobile-child-location-history-search"),
    path("mobile/location-history/<int:location_id>/", MobileLocationHistoryDetailView.as_view(), name="mobile-location-history-detail"),
    path("mobile/children/<int:child_id>/map-context/", MobileChildMapContextView.as_view(), name="mobile-child-map-context"),
    path("mobile/children/<int:child_id>/alerts/", MobileChildAlertsView.as_view(), name="mobile-child-alerts"),
    path("ubicaciones/contexto/", MobileLocationContextView.as_view(), name="ubicaciones-contexto"),
    path("ubicaciones/registrar/", GeographicLocationRegisterView.as_view(), name="ubicaciones-registrar"),
    path("ubicaciones/historial/", GeographicLocationHistoryView.as_view(), name="ubicaciones-historial"),
    path("ubicaciones/nino/<int:nino_id>/", GeographicLocationByChildView.as_view(), name="ubicaciones-nino"),
    path("monitoreo/analizar/", MonitoringAnalyzeView.as_view(), name="monitoreo-analizar"),
    path("monitoreo/historial/", MonitoringHistoryView.as_view(), name="monitoreo-historial"),
    path("monitoreo/estado-actual/<int:child_id>/", MonitoringCurrentStatusView.as_view(), name="monitoreo-estado-actual"),
    path("monitoreo/configuracion/", MonitoringConfigView.as_view(), name="monitoreo-configuracion"),
    path("monitoreo/metricas/", MonitoringMetricsView.as_view(), name="monitoreo-metricas"),
    path("security-alerts/", SecurityAlertsView.as_view(), name="security-alerts"),
    path("security-alerts/stats/", SecurityAlertStatsView.as_view(), name="security-alerts-stats"),
    path("security-alerts/by-child/<int:child_id>/", SecurityAlertsByChildView.as_view(), name="security-alerts-by-child"),
    path("security-alerts/<int:alert_id>/", SecurityAlertDetailView.as_view(), name="security-alert-detail"),
    path("security-alerts/<int:alert_id>/status/", SecurityAlertStatusUpdateView.as_view(), name="security-alert-status"),
    path("security-alerts/<int:alert_id>/history/", SecurityAlertHistoryView.as_view(), name="security-alert-history"),
    path("mobile/security-alerts/stats/", MobileSecurityAlertStatsView.as_view(), name="mobile-security-alerts-stats"),
    path("mobile/security-alerts/<int:alert_id>/", MobileSecurityAlertDetailView.as_view(), name="mobile-security-alert-detail"),
    path("mobile/security-alerts/<int:alert_id>/status/", MobileSecurityAlertStatusUpdateView.as_view(), name="mobile-security-alert-status"),
    path("mobile/security-alerts/", MobileSecurityAlertsView.as_view(), name="mobile-security-alerts"),
    path("roles/", RoleListCreateView.as_view(), name="roles-list-create"),
    path("roles/stats/", RoleStatsView.as_view(), name="roles-stats"),
    path("roles/<int:role_id>/", RoleDetailView.as_view(), name="roles-detail"),
    path("roles/<int:role_id>/status/", RoleStatusView.as_view(), name="roles-status"),
    path("modules/", ModuleListView.as_view(), name="modules-list"),
    path("permissions/", PermissionListView.as_view(), name="permissions-list"),
    path("regents/", RegentListCreateView.as_view(), name="regents-list-create"),
    path("regents/options/", RegentOptionsView.as_view(), name="regents-options"),
    path("regents/stats/", RegentStatsView.as_view(), name="regents-stats"),
    path("regents/educational-centers/", RegentEducationalCenterOptionsView.as_view(), name="regents-educational-centers"),
    path("regents/<int:regent_id>/", RegentDetailView.as_view(), name="regents-detail"),
    path("regents/<int:regent_id>/status/", RegentStatusView.as_view(), name="regents-status"),
    path("risk-zones/", RiskZoneListCreateView.as_view(), name="risk-zones-list-create"),
    path("risk-zones/stats/", RiskZoneStatsView.as_view(), name="risk-zones-stats"),
    path("risk-zones/validate-polygon/", RiskZoneValidatePolygonView.as_view(), name="risk-zones-validate-polygon"),
    path("risk-zones/calculate/", RiskZoneCalculateView.as_view(), name="risk-zones-calculate"),
    path("risk-zones/<int:risk_zone_id>/", RiskZoneDetailView.as_view(), name="risk-zones-detail"),
    path("risk-zones/<int:risk_zone_id>/status/", RiskZoneStatusView.as_view(), name="risk-zones-status"),
    path("safe-areas/", SafeAreaListCreateView.as_view(), name="safe-areas-list-create"),
    path("safe-areas/stats/", SafeAreaStatsView.as_view(), name="safe-areas-stats"),
    path("safe-areas/validate-polygon/", SafeAreaValidatePolygonView.as_view(), name="safe-areas-validate-polygon"),
    path("safe-areas/calculate/", SafeAreaCalculateView.as_view(), name="safe-areas-calculate"),
    path("safe-areas/by-center/<int:center_id>/", SafeAreaByCenterView.as_view(), name="safe-areas-by-center"),
    path("safe-areas/<int:safe_area_id>/", SafeAreaDetailView.as_view(), name="safe-areas-detail"),
    path("safe-areas/<int:safe_area_id>/status/", SafeAreaStatusView.as_view(), name="safe-areas-status"),
    path("safe-areas/<int:safe_area_id>/history/", SafeAreaHistoryView.as_view(), name="safe-areas-history"),
    path("children/", ChildListCreateView.as_view(), name="children-list-create"),
    path("children/stats/", ChildStatsView.as_view(), name="children-stats"),
    path("children/<int:child_id>/", ChildDetailView.as_view(), name="children-detail"),
    path("children/<int:child_id>/status/", ChildStatusView.as_view(), name="children-status"),
    path("students/", StudentListCreateView.as_view(), name="students-list-create"),
    path("students/stats/", StudentStatsView.as_view(), name="students-stats"),
    path("students/active/", StudentActiveView.as_view(), name="students-active"),
    path("students/without-gps/", StudentWithoutGpsView.as_view(), name="students-without-gps"),
    path("students/by-center/<int:center_id>/", StudentByCenterView.as_view(), name="students-by-center"),
    path("students/<int:student_id>/", StudentDetailView.as_view(), name="students-detail"),
    path("students/<int:student_id>/status/", StudentStatusView.as_view(), name="students-status"),
    path("students/<int:student_id>/history/", StudentHistoryView.as_view(), name="students-history"),
    path("child-tutor-associations/", ChildTutorAssociationListCreateView.as_view(), name="child-tutor-associations-list-create"),
    path("child-tutor-associations/stats/", ChildTutorAssociationStatsView.as_view(), name="child-tutor-associations-stats"),
    path("child-tutor-associations/by-child/<int:child_id>/", ChildTutorAssociationByChildView.as_view(), name="child-tutor-associations-by-child"),
    path("child-tutor-associations/by-tutor/<int:tutor_id>/", ChildTutorAssociationByTutorView.as_view(), name="child-tutor-associations-by-tutor"),
    path("child-tutor-associations/<int:association_id>/", ChildTutorAssociationDetailView.as_view(), name="child-tutor-associations-detail"),
    path("child-tutor-associations/<int:association_id>/history/", ChildTutorAssociationHistoryView.as_view(), name="child-tutor-associations-history"),
    path("tutors/", TutorListCreateView.as_view(), name="tutors-list-create"),
    path("tutors/stats/", TutorStatsView.as_view(), name="tutors-stats"),
    path("tutors/<int:tutor_id>/", TutorDetailView.as_view(), name="tutors-detail"),
    path("tutors/<int:tutor_id>/status/", TutorStatusView.as_view(), name="tutors-status"),
    path("tutors/<int:tutor_id>/children/", TutorChildrenView.as_view(), name="tutors-children"),
    path("tutors/<int:tutor_id>/mobile-account/", TutorMobileAccountView.as_view(), name="tutors-mobile-account"),
    path("tutors/<int:tutor_id>/reset-password/", TutorResetPasswordView.as_view(), name="tutors-reset-password"),
    path("educational-centers/", EducationalCenterListCreateView.as_view(), name="educational-centers-list-create"),
    path("educational-centers/stats/", EducationalCenterStatsView.as_view(), name="educational-centers-stats"),
    path("educational-centers/<int:center_id>/", EducationalCenterDetailView.as_view(), name="educational-centers-detail"),
    path("educational-centers/<int:center_id>/status/", EducationalCenterStatusView.as_view(), name="educational-centers-status"),
    path("gps-devices/", GPSDeviceListCreateView.as_view(), name="gps-devices-list-create"),
    path("gps-devices/stats/", GPSDeviceStatsView.as_view(), name="gps-devices-stats"),
    path("gps-devices/available/", GPSDeviceAvailableView.as_view(), name="gps-devices-available"),
    path("gps-devices/<int:gps_device_id>/", GPSDeviceDetailView.as_view(), name="gps-devices-detail"),
    path("gps-devices/<int:gps_device_id>/status/", GPSDeviceStatusView.as_view(), name="gps-devices-status"),
    path("gps-devices/<int:gps_device_id>/history/", GPSDeviceHistoryView.as_view(), name="gps-devices-history"),
]
