from django.urls import path

from .views import (
    ChildDetailView,
    ChildListCreateView,
    ChildStatsView,
    ChildStatusView,
    EducationalCenterListView,
    GPSDeviceListView,
    LoginView,
    ModuleListView,
    PermissionListView,
    RoleDetailView,
    RoleListCreateView,
    RoleStatsView,
    RoleStatusView,
    TutorChildrenView,
    TutorDetailView,
    TutorListCreateView,
    TutorMobileAccountView,
    TutorResetPasswordView,
    TutorStatsView,
    TutorStatusView,
)

urlpatterns = [
    path("auth/login/", LoginView.as_view(), name="login"),
    path("roles/", RoleListCreateView.as_view(), name="roles-list-create"),
    path("roles/stats/", RoleStatsView.as_view(), name="roles-stats"),
    path("roles/<int:role_id>/", RoleDetailView.as_view(), name="roles-detail"),
    path("roles/<int:role_id>/status/", RoleStatusView.as_view(), name="roles-status"),
    path("modules/", ModuleListView.as_view(), name="modules-list"),
    path("permissions/", PermissionListView.as_view(), name="permissions-list"),
    path("children/", ChildListCreateView.as_view(), name="children-list-create"),
    path("children/stats/", ChildStatsView.as_view(), name="children-stats"),
    path("children/<int:child_id>/", ChildDetailView.as_view(), name="children-detail"),
    path("children/<int:child_id>/status/", ChildStatusView.as_view(), name="children-status"),
    path("tutors/", TutorListCreateView.as_view(), name="tutors-list-create"),
    path("tutors/stats/", TutorStatsView.as_view(), name="tutors-stats"),
    path("tutors/<int:tutor_id>/", TutorDetailView.as_view(), name="tutors-detail"),
    path("tutors/<int:tutor_id>/status/", TutorStatusView.as_view(), name="tutors-status"),
    path("tutors/<int:tutor_id>/children/", TutorChildrenView.as_view(), name="tutors-children"),
    path("tutors/<int:tutor_id>/mobile-account/", TutorMobileAccountView.as_view(), name="tutors-mobile-account"),
    path("tutors/<int:tutor_id>/reset-password/", TutorResetPasswordView.as_view(), name="tutors-reset-password"),
    path("educational-centers/", EducationalCenterListView.as_view(), name="educational-centers-list"),
    path("gps-devices/", GPSDeviceListView.as_view(), name="gps-devices-list"),
]
