# Generated by Django 5.1.10 on 2026-06-13 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_safearea_and_history_cu7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalcenter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ChildTutorAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tutor_associations', to='users.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tutor_associations_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tutor_associations_deactivated', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tutor_associations', to='users.tutor')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ChildTutorAssociationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREACION', 'Creacion'), ('ELIMINACION', 'Eliminacion'), ('REACTIVACION', 'Reactivacion')], max_length=20)),
                ('detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='users.childtutorassociation')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tutor_association_history_entries', to='users.child')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tutor_association_history_entries', to='users.tutor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tutor_association_history_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='childtutorassociation',
            constraint=models.UniqueConstraint(fields=('child', 'tutor'), name='unique_child_tutor_association'),
        ),
    ]
