# Generated by Django 5.1.10 on 2026-06-13 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_educationalcenter_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('precision', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('device_timestamp', models.DateTimeField()),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('REENVIADO', 'Reenviado'), ('PENDIENTE', 'Pendiente')], default='ENVIADO', max_length=20)),
                ('inside_safe_area', models.BooleanField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_host', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geographic_locations', to='users.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geographic_locations_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geographic_locations', to='users.gpsdevice')),
            ],
            options={
                'ordering': ('-device_timestamp', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('device', 'device_timestamp'), name='unique_geographic_location_device_timestamp')],
            },
        ),
    ]
