# Generated by Django 5.1.10 on 2026-06-13 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_geographiclocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_time_between_alerts_min', models.PositiveIntegerField(default=5)),
                ('min_distance_state_change_m', models.PositiveIntegerField(default=10)),
                ('max_gps_accuracy_m', models.PositiveIntegerField(default=50)),
                ('enable_risk_zones', models.BooleanField(default=True)),
                ('register_errors_as_pending', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitoring configuration',
                'verbose_name_plural': 'Monitoring configuration',
            },
        ),
        migrations.CreateModel(
            name='MonitoringAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('SALIDA_AREA_SEGURA', 'Salida de area segura'), ('INGRESO_ZONA_RIESGO', 'Ingreso a zona de riesgo'), ('ERROR_MONITOREO', 'Error de monitoreo')], max_length=30)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SEGURO', 'Seguro'), ('FUERA_AREA', 'Fuera de area'), ('ZONA_RIESGO', 'Zona de riesgo'), ('ERROR', 'Error'), ('PENDIENTE', 'Pendiente')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_alerts', to='users.child')),
                ('location_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_alerts', to='users.geographiclocation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('polygon', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('educational_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_zones', to='users.educationalcenter')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MonitoringHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SEGURO', 'Seguro'), ('FUERA_AREA', 'Fuera de area'), ('ZONA_RIESGO', 'Zona de riesgo'), ('ERROR', 'Error'), ('PENDIENTE', 'Pendiente')], max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('distance_to_perimeter_m', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='users.monitoringalert')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_history_entries', to='users.child')),
                ('location_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_entries', to='users.geographiclocation')),
                ('risk_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_history_entries', to='users.riskzone')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
