# Generated by Django 5.1.10 on 2026-06-13 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_monitoringconfig_monitoringalert_riskzone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringalert',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='attended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts_attended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='educational_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_alerts', to='users.educationalcenter'),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='event_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='gps_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_alerts', to='users.gpsdevice'),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='monitoring_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_security_alerts', to='users.monitoringhistory'),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='priority',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='risk_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_alerts', to='users.riskzone'),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monitoringalert',
            name='workflow_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=12),
        ),
        migrations.CreateModel(
            name='SecurityAlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREADA', 'Creada'), ('VISTA', 'Vista'), ('ATENDIDA', 'Atendida'), ('CERRADA', 'Cerrada'), ('REABIERTA', 'Reabierta'), ('ACTUALIZADA', 'Actualizada')], max_length=15)),
                ('previous_status', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('CERRADA', 'Cerrada')], max_length=12, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('CERRADA', 'Cerrada')], max_length=12, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_history_entries', to='users.monitoringalert')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alert_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-changed_at',),
            },
        ),
    ]
