# Generated by Django 5.1.10 on 2026-06-13 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_monitoringalert_accuracy_monitoringalert_attended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskzone',
            name='area_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='riskzone',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='riskzone',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='riskzone',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='riskzone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_zones_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskzone',
            name='perimeter_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='riskzone',
            name='risk_type',
            field=models.CharField(choices=[('DELINCUENCIA', 'Delincuencia'), ('TRAFICO', 'Tráfico'), ('OBRA', 'Obra'), ('RIO_CANAL', 'Río o canal'), ('ZONA_OSCURA', 'Zona oscura'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='riskzone',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_zones_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riskzone',
            name='educational_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_zones', to='users.educationalcenter'),
        ),
        migrations.AlterField(
            model_name='riskzone',
            name='severity',
            field=models.CharField(choices=[('INFORMATIVO', 'Informativo'), ('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=12),
        ),
    ]
