# Generated by Django 5.1.10 on 2026-06-16 04:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_riskzone_soft_delete_and_contract_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='battery_level',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='brand',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_devices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='status',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('PERDIDO', 'Perdido'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_devices_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GPSDeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREACION', 'Creacion'), ('EDICION', 'Edicion'), ('ASIGNACION', 'Asignacion'), ('DESASIGNACION', 'Desasignacion'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('ACTIVACION', 'Activacion'), ('DESACTIVACION', 'Desactivacion'), ('ELIMINACION_CONTROLADA', 'Eliminacion controlada')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('previous_status', models.CharField(blank=True, choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('PERDIDO', 'Perdido'), ('INACTIVO', 'Inactivo')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('PERDIDO', 'Perdido'), ('INACTIVO', 'Inactivo')], max_length=20)),
                ('previous_is_active', models.BooleanField(blank=True, null=True)),
                ('new_is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gps_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='users.gpsdevice')),
                ('new_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_history_new_entries', to='users.child')),
                ('previous_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_history_previous_entries', to='users.child')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
