# Generated by Django 5.1.10 on 2026-06-16 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_gpsdevice_battery_level_gpsdevice_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='ci',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='child',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='desactivado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='child',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], default='OTRO', max_length=12),
        ),
        migrations.AddField(
            model_name='child',
            name='nivel',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], default='PRIMARIA', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='nombre_contacto_emergencia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='child',
            name='paralelo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='rude',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='child',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='child',
            name='telefono_contacto_emergencia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='child',
            name='turno',
            field=models.CharField(choices=[('MANANA', 'Manana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], default='MANANA', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREACION', 'Creacion'), ('EDICION', 'Edicion'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('ASIGNACION_GPS', 'Asignacion GPS'), ('LIBERACION_GPS', 'Liberacion GPS'), ('ELIMINACION', 'Eliminacion')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('previous_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history_entries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='users.child')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
