# Generated by Django 5.1.10 on 2026-06-22 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_child_ci_child_created_by_child_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_method', models.CharField(choices=[('BIOMETRIA', 'Biometria del dispositivo'), ('HUELLA', 'Huella dactilar'), ('ROSTRO', 'Reconocimiento facial')], default='BIOMETRIA', max_length=20)),
                ('source_platform', models.CharField(default='mobile', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_records', to='users.child')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_records_confirmed', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_records', to='users.tutor')),
            ],
            options={
                'ordering': ('-confirmed_at', '-id'),
            },
        ),
    ]
